site_name: Carlton
repo_url: https://github.com/lealdouglas/carlton
repo_name: lealdouglas/carlton
edit_uri: tree/main/docs

theme:
  name: readthedocs
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/logo.png

markdown_extensions:
  - attr_list
  - admonition

extra_css:
  - stylesheets/extra.css

watch:
  - carlton
plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [carlton]
